# Development docker-compose.yml
version: "3.5"

services:
    devbox:
        container_name: devbox-nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:80"
        volumes:
            - .:/app:cached
        restart: unless-stopped
        depends_on:
            - devbox-service

    devbox-service:
        container_name: devbox-service
        build:
            context: .
        volumes:
            - .:/app:cached
            - ./docker/service/php.ini:/usr/local/etc/php/conf.d/99-app.ini
            - ./docker/service/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: unless-stopped
        environment:
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_SECRET: ${APP_SECRET}
        env_file:
            - .env
        depends_on:
            - mysql
            - redis

    mysql:
        image: mysql:latest
        container_name: devbox-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_ROOT_USER: root
            MYSQL_DATABASE: ${DATABASE_NAME}
        ports:
            - "3308:3306"
        volumes:
            - database-volume:/var/lib/mysql

    redis:
        image: redis:7.0.4-alpine
        container_name: devbox-redis
        command: redis-server --save 20 1 --loglevel warning
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - cache-volume:/data

volumes:
    database-volume:
        driver: "local"
    cache-volume:
        driver: "local"
