store_analytics:
    path: /store
    controller: App\Controller\LogAnalyticsController::store
    methods: POST

analytics:
    path: /count
    controller: App\Controller\LogAnalyticsController::count
    methods: GET
