name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  directory: ./devbox

jobs:
  code-coverage:
    name: "Code coverage and analysis"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.directory }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: "8.1"

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          php -r "file_exists('.env.local') || copy('.env.test', '.env.local');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run static analysis
        run: ./vendor/bin/phpstan analyze src tests --memory-limit=1G

      - name: Run PHP Fixer
        run: ./vendor/bin/php-cs-fixer --config=.php-cs-fixer.php fix src tests

      - name: Run PHPLint
        run: ./vendor/bin/phplint

  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: legal_one
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    defaults:
      run:
        working-directory: ${{ env.directory }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: "8.1"
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, mysqli

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run migrations
        run: |
          php bin/console doctrine:database:drop --if-exists --force --env=test
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
          php bin/console doctrine:fixtures:load --env=test --no-interaction
        env:
          DATABASE_URL: mysql://root:legal_one@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/legal_one

      - name: Execute tests
        run: php bin/phpunit
        env:
          DATABASE_URL: mysql://root:legal_one@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/legal_one
